# Generated by Django 3.2.12 on 2022-03-07 03:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0006_auto_20220307_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahallenufus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahalleadi', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('nufusdensity', models.FloatField()),
            ],
            options={
                'db_table': 'mahallenufus',
                'managed': False,
            },
        ),
    ]
