# Generated by Django 3.2.12 on 2022-03-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_auto_20220306_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='metroasafasurak',
        ),
    ]
